const http=require('http');const fs=require('fs');const path=require('path');const {URL}=require('url');
const PORT=Number(process.env.PORT||3000),ROOT=__dirname,SB_URL=process.env.SUPABASE_URL,SB_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_ANON_KEY,connected=Boolean(SB_URL&&SB_KEY),DATA_FILE=path.join(ROOT,'data.json');
const initialData={products:[{id:'p1',sku:'SP-001',name:'Nova X Pro',brand:'Nexora',category:'Smartphone',price:12999000,stock:12,min_stock:5},{id:'p2',sku:'SP-002',name:'Pixel Air 5',brand:'Orbis',category:'Smartphone',price:8499000,stock:4,min_stock:5},{id:'p3',sku:'LP-001',name:'WorkBook 14',brand:'Nexora',category:'Laptop',price:15499000,stock:8,min_stock:3},{id:'p4',sku:'AC-001',name:'Earbuds Quiet',brand:'Sonic',category:'Aksesoris',price:899000,stock:18,min_stock:5}],sales:[{invoice_no:'INV-20260924-001',customer:'Raka Pratama',sale_date:'2026-09-24',total:13898000,status:'Selesai'},{invoice_no:'INV-20260923-002',customer:'Nadia Putri',sale_date:'2026-09-23',total:899000,status:'Selesai'}],returns:[{return_no:'RET-20260924-001',customer:'Nadia Putri',return_date:'2026-09-24',refund_amount:899000,status:'Diproses'}]};
function loadData(){try{if(fs.existsSync(DATA_FILE))return JSON.parse(fs.readFileSync(DATA_FILE,'utf8'))}catch(e){console.error('Gagal baca data.json:',e.message)}return JSON.parse(JSON.stringify(initialData))}
function saveData(d){try{fs.writeFileSync(DATA_FILE,JSON.stringify(d,null,2),'utf8')}catch(e){console.error('Gagal simpan data.json:',e.message)}}
let demo=loadData();
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data))}
function file(res,name,type){fs.readFile(path.join(ROOT,name),(e,d)=>e?json(res,404,{error:'Not found'}):(res.writeHead(200,{'Content-Type':type}),res.end(d)))}
function body(req){return new Promise((ok,no)=>{let b='';req.on('data',c=>b+=c);req.on('end',()=>{try{ok(b?JSON.parse(b):{})}catch(e){no(Error('JSON tidak valid'))}});req.on('error',no)})}
async function sb(table,query='',opts={}){const r=await fetch(`${SB_URL}/rest/v1/${table}${query}`,{method:opts.method||'GET',headers:{apikey:SB_KEY,Authorization:`Bearer ${SB_KEY}`,'Content-Type':'application/json',Prefer:'return=representation'},body:opts.body?JSON.stringify(opts.body):undefined});if(!r.ok)throw Error(await r.text());return r.status===204?null:r.json()}
async function api(req,res,url){
  try{
    if(req.method==='GET'&&url.pathname==='/api/dashboard'){const d=connected?(await sb('dashboard_summary','?select=*'))[0]:{product_count:demo.products.length,low_stock_count:demo.products.filter(x=>x.stock<=x.min_stock).length,monthly_revenue:demo.sales.reduce((a,x)=>a+x.total,0),pending_returns:demo.returns.length};return json(res,200,d)}
    const map={'/api/products':['products','?select=*,categories(name)&order=stock.asc',demo.products],'/api/sales':['sales','?select=*,customers(name)&order=sale_date.desc&limit=20',demo.sales],'/api/returns':['returns','?select=*,customers(name)&order=return_date.desc&limit=20',demo.returns]};
    if(req.method==='GET'&&map[url.pathname]){const [t,q,f]=map[url.pathname];return json(res,200,connected?await sb(t,q):f)}
    if(req.method==='POST'&&url.pathname==='/api/products'){const b=await body(req);if(!b.name||!b.sku||!b.brand)return json(res,400,{error:'name, sku, brand wajib diisi'});const row={id:'p'+Date.now(),sku:b.sku,name:b.name,brand:b.brand,category:b.category||'Umum',price:Number(b.price||0),stock:Number(b.stock||0),min_stock:Number(b.min_stock||5)};if(connected){const[c]=await sb('products','',{method:'POST',body:row});return json(res,201,c)}demo.products.push(row);saveData(demo);return json(res,201,row)}
    if(req.method==='PUT'&&/^\/api\/products\/[\w-]+$/.test(url.pathname)){const id=url.pathname.split('/').pop(),b=await body(req),i=demo.products.findIndex(p=>p.id===id);if(i===-1)return json(res,404,{error:'Produk tidak ditemukan'});demo.products[i]={...demo.products[i],name:b.name??demo.products[i].name,sku:b.sku??demo.products[i].sku,brand:b.brand??demo.products[i].brand,category:b.category??demo.products[i].category,price:b.price!==undefined?Number(b.price):demo.products[i].price,stock:b.stock!==undefined?Number(b.stock):demo.products[i].stock,min_stock:b.min_stock!==undefined?Number(b.min_stock):demo.products[i].min_stock};saveData(demo);return json(res,200,demo.products[i])}
    if(req.method==='DELETE'&&/^\/api\/products\/[\w-]+$/.test(url.pathname)){const id=url.pathname.split('/').pop(),i=demo.products.findIndex(p=>p.id===id);if(i===-1)return json(res,404,{error:'Produk tidak ditemukan'});demo.products.splice(i,1);saveData(demo);return json(res,200,{ok:true})}
    if(req.method==='POST'&&url.pathname==='/api/sales'){const b=await body(req),p=demo.products.find(x=>x.id===b.product_id);if(!p)return json(res,400,{error:'Produk tidak ditemukan'});const q=Number(b.quantity||1),total=p.price*q,row={invoice_no:'INV-'+Date.now(),customer:b.customer||'-',sale_date:new Date().toISOString().slice(0,10),total,status:'Selesai'};if(connected){const[c]=await sb('sales','',{method:'POST',body:{invoice_no:row.invoice_no,total,status:'Selesai'}});return json(res,201,c)}demo.sales.unshift(row);p.stock=Math.max(0,p.stock-q);saveData(demo);return json(res,201,row)}
    if(req.method==='POST'&&url.pathname==='/api/returns'){const b=await body(req),row={return_no:'RET-'+Date.now(),customer:b.customer||'-',return_date:new Date().toISOString().slice(0,10),refund_amount:Number(b.refund_amount||0),status:'Diproses'};if(connected){const[c]=await sb('returns','',{method:'POST',body:{return_no:row.return_no,reason:b.notes||'-',refund_amount:row.refund_amount,status:'Diproses'}});return json(res,201,c)}demo.returns.unshift(row);saveData(demo);return json(res,201,row)}
    return json(res,404,{error:'Endpoint tidak ditemukan'})
  }catch(e){return json(res,500,{error:e.message})}
}
http.createServer((req,res)=>{const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(u.pathname.startsWith('/api/'))return api(req,res,u);if(req.method!=='GET')return json(res,405,{error:'Method tidak diizinkan'});const files={'/':['index.html','text/html'],'/index.html':['index.html','text/html'],'/styles.css':['styles.css','text/css'],'/script.js':['script.js','text/javascript']};return files[u.pathname]?file(res,...files[u.pathname]):json(res,404,{error:'Not found'})}).listen(PORT,()=>console.log(`GadgetFlow: http://localhost:${PORT} | ${connected?'Supabase':'mode demo (data permanen di data.json)'}`));