create extension if not exists pgcrypto;
create table if not exists customers(id uuid primary key default gen_random_uuid(),name text not null,phone text,email text unique,address text,created_at timestamptz default now());
create table if not exists employees(id uuid primary key default gen_random_uuid(),name text not null,role text not null default 'Kasir',email text unique,created_at timestamptz default now());
create table if not exists categories(id uuid primary key default gen_random_uuid(),name text unique not null,description text);
create table if not exists suppliers(id uuid primary key default gen_random_uuid(),name text not null,phone text,email text,address text);
create table if not exists products(id uuid primary key default gen_random_uuid(),category_id uuid not null references categories(id),supplier_id uuid references suppliers(id),sku text unique not null,name text not null,brand text not null,price numeric(14,2) check(price>=0),stock int default 0 check(stock>=0),min_stock int default 5 check(min_stock>=0),warranty_months int default 12);
create table if not exists sales(id uuid primary key default gen_random_uuid(),customer_id uuid not null references customers(id),employee_id uuid not null references employees(id),invoice_no text unique not null,sale_date timestamptz default now(),subtotal numeric(14,2) default 0,discount numeric(14,2) default 0,total numeric(14,2) default 0,status text default 'Selesai',notes text);
create table if not exists sale_items(id uuid primary key default gen_random_uuid(),sale_id uuid not null references sales(id) on delete cascade,product_id uuid not null references products(id),quantity int not null check(quantity>0),unit_price numeric(14,2) not null,line_total numeric(14,2) generated always as(quantity*unit_price) stored,unique(sale_id,product_id));
create table if not exists returns(id uuid primary key default gen_random_uuid(),sale_id uuid not null references sales(id),customer_id uuid not null references customers(id),employee_id uuid not null references employees(id),return_no text unique not null,return_date timestamptz default now(),reason text not null,refund_amount numeric(14,2) default 0,status text default 'Diproses',notes text);
create table if not exists return_items(id uuid primary key default gen_random_uuid(),return_id uuid not null references returns(id) on delete cascade,product_id uuid not null references products(id),quantity int not null check(quantity>0),condition text default 'Baik',refund_amount numeric(14,2) default 0);
create table if not exists payments(id uuid primary key default gen_random_uuid(),sale_id uuid not null references sales(id) on delete cascade,payment_date timestamptz default now(),method text not null,amount numeric(14,2) not null,reference_no text,status text default 'Berhasil');
create or replace view dashboard_summary as select (select count(*) from products) product_count,(select count(*) from products where stock<=min_stock) low_stock_count,(select coalesce(sum(total),0) from sales where status='Selesai' and sale_date>=date_trunc('month',now())) monthly_revenue,(select count(*) from returns where status in('Diproses','Disetujui')) pending_returns;
-- ERD 10 entitas: customers, employees, categories, suppliers, products, sales, sale_items, returns, return_items, payments.
